import "./globals.css";
import { Inter } from "next/font/google";
import { jost, noto, notojp } from "./fonts";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Artisan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={`${jost.variable} ${notojp.variable} ${noto.variable}`}>
        {children}
      </body>
    </html>
  );
}
